import AppKit

struct ClipItem: Identifiable {
    enum Content {
        case text(String)
        case image(NSImage)
    }
    let id = UUID()
    let content: Content
    let date: Date
    let sourceBundleID: String?

    var text: String? { if case .text(let s) = content { s } else { nil } }
}

/// Clipboard history with privacy defaults:
/// - in memory only unless the user opts into persistence (text only, never images)
/// - skips items marked concealed/transient/auto-generated (password managers set these)
/// - skips copies made while an excluded app is frontmost
/// - one-click clear
/// Polls only `changeCount`, which is cheap, and reads contents only when it changes.
@MainActor
final class ClipboardMonitor: ObservableObject {
    @Published private(set) var items: [ClipItem] = []
    @Published var isPaused = false

    static let maxItems = 30
    private static let maxImages = 8
    private static let skipTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
    ]

    private let pb = NSPasteboard.general
    private var lastChange = NSPasteboard.general.changeCount
    private var timer: Timer?
    private var persistURL: URL { AppPaths.support.appendingPathComponent("clipboard.json") }

    func start() {
        guard timer == nil else { return }
        if Settings.shared.clipboardPersist { loadPersisted() }
        lastChange = pb.changeCount
        let t = Timer(timeInterval: 0.75, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.poll() }
        }
        t.tolerance = 0.3
        RunLoop.main.add(t, forMode: .common)
        timer = t
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    func clear() {
        items.removeAll()
        try? FileManager.default.removeItem(at: persistURL)
    }

    func remove(_ item: ClipItem) {
        items.removeAll { $0.id == item.id }
        persist()
    }

    /// Puts an item back on the pasteboard and moves it to the top.
    func copy(_ item: ClipItem) {
        pb.clearContents()
        switch item.content {
        case .text(let s): pb.setString(s, forType: .string)
        case .image(let img): pb.writeObjects([img])
        }
        lastChange = pb.changeCount // don't re-capture our own write
        items.removeAll { $0.id == item.id }
        items.insert(ClipItem(content: item.content, date: Date(), sourceBundleID: item.sourceBundleID), at: 0)
        persist()
    }

    private func poll() {
        let count = pb.changeCount
        guard count != lastChange else { return }
        lastChange = count
        guard !isPaused else { return }

        let types = Set((pb.types ?? []).map(\.rawValue))
        if !types.isDisjoint(with: Self.skipTypes) { return }
        let front = NSWorkspace.shared.frontmostApplication?.bundleIdentifier
        if let front, Settings.shared.clipboardExcludedApps.contains(front) { return }

        if let s = pb.string(forType: .string) {
            let trimmed = s.trimmingCharacters(in: .whitespacesAndNewlines)
            guard !trimmed.isEmpty else { return }
            if items.first?.text == s { return }
            items.removeAll { $0.text == s }
            insert(ClipItem(content: .text(s), date: Date(), sourceBundleID: front))
        } else if types.contains(NSPasteboard.PasteboardType.png.rawValue) || types.contains(NSPasteboard.PasteboardType.tiff.rawValue),
                  let img = NSImage(pasteboard: pb) {
            insert(ClipItem(content: .image(img), date: Date(), sourceBundleID: front))
            // keep only the newest few images; they're big
            var seen = 0
            items.removeAll { item in
                guard case .image = item.content else { return false }
                seen += 1
                return seen > Self.maxImages
            }
        }
    }

    private func insert(_ item: ClipItem) {
        items.insert(item, at: 0)
        if items.count > Self.maxItems { items.removeLast(items.count - Self.maxItems) }
        persist()
    }

    /// Sample data for `--snapshot --demo` marketing renders.
    func setDemo(_ items: [ClipItem]) { self.items = items }

    // MARK: Opt-in persistence (text only)

    private struct Record: Codable { let text: String; let date: Date; let source: String? }

    private func persist() {
        guard Settings.shared.clipboardPersist else { return }
        let records = items.compactMap { i in i.text.map { Record(text: $0, date: i.date, source: i.sourceBundleID) } }
        if let data = try? JSONEncoder().encode(records) { try? data.write(to: persistURL, options: [.atomic, .completeFileProtection]) }
    }

    private func loadPersisted() {
        guard items.isEmpty, let data = try? Data(contentsOf: persistURL),
              let records = try? JSONDecoder().decode([Record].self, from: data) else { return }
        items = records.map { ClipItem(content: .text($0.text), date: $0.date, sourceBundleID: $0.source) }
    }

    /// Called when the user turns persistence off: delete what's on disk right away.
    func persistenceChanged(_ on: Bool) {
        if on { persist() } else { try? FileManager.default.removeItem(at: persistURL) }
    }
}
